# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - make copy-examples

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: []

python:
  install:
    - requirements: docs/requirements.txt
